# -*- coding: utf-8 -*-
"""Copy of Capstone Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkqE3T3rJa_CEt65pY4m1FiwNtBqYRnE
"""

from google.colab import drive
drive.mount('/content/drive')

!grep -n "pip install transformers" /content/drive/MyDrive/*.ipynb 2>/dev/null || echo "Can't search that way in Colab, do it manually below"

import pandas as pd

import pandas as pd

# Search for the file by name across your mounted Drive
!find /content/drive/MyDrive -iname "*suicidal_ideation*"

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/suicidal_ideation_reddit_annotated.csv')
display(df.head())

# Check for missing values
print('Missing values in each column:')
display(df.isnull().sum())

# Check class distribution of the 'label' column
print('\nClass distribution of the label column:')
display(df['label'].value_counts())

# Display the percentage distribution as well
print('\nClass distribution (percentages):')
display(df['label'].value_counts(normalize=True) * 100)

# Fill missing values in 'usertext' with an empty string
df['usertext'] = df['usertext'].fillna('')

print('Missing values after filling:')
display(df.isnull().sum())

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import SMOTE
from collections import Counter

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower() # Lowercasing
    text = ''.join([char for char in text if char.isalnum() or char.isspace()]) # Punctuation removal (keep alphanumeric and spaces)
    tokens = text.split() # Tokenization
    tokens = [word for word in tokens if word not in stop_words] # Stop-word filtering
    tokens = [lemmatizer.lemmatize(word) for word in tokens] # Lemmatization
    return ' '.join(tokens)

print('Applying text preprocessing...')
df['processed_text'] = df['usertext'].apply(preprocess_text)
print('Text preprocessing complete.')

# TF-IDF Vectorization
print('Applying TF-IDF Vectorization...')
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limiting features for manageability
X = tfidf_vectorizer.fit_transform(df['processed_text'])
y = df['label']
print('TF-IDF Vectorization complete.')

# Class Balancing using SMOTE
print('Applying SMOTE for class balancing...')
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print('SMOTE complete.')

print('\nOriginal class distribution:', Counter(y))
print('Resampled class distribution:', Counter(y_resampled))

import matplotlib.pyplot as plt
import seaborn as sns

# --- Domain-derived features ---
df['word_count'] = df['usertext'].apply(lambda x: len(str(x).split()))
df['char_count'] = df['usertext'].apply(lambda x: len(str(x)))

first_person_words = {'i', 'me', 'my', 'mine', 'myself'}
df['first_person_count'] = df['processed_text'].apply(
    lambda x: sum(1 for word in x.split() if word in first_person_words)
)

print("Domain-derived features added: word_count, char_count, first_person_count")
display(df[['word_count', 'char_count', 'first_person_count']].describe())

# --- Distribution EDA ---
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Word count distribution by label
sns.histplot(data=df, x='word_count', hue='label', bins=50, ax=axes[0], element='step')
axes[0].set_xlim(0, 500)
axes[0].set_title('Word Count Distribution by Label')

# Label distribution
sns.countplot(data=df, x='label', ax=axes[1])
axes[1].set_title('Class Distribution (0=Non-Risk, 1=Suicidal Ideation)')

# First-person pronoun usage by label
sns.boxplot(data=df, x='label', y='first_person_count', ax=axes[2])
axes[2].set_ylim(0, 30)
axes[2].set_title('First-Person Pronoun Usage by Label')

plt.tight_layout()
plt.savefig('/content/eda_distributions.png', dpi=150)
plt.show()

# Relationship check: average word count and first-person usage by label
print("\nAverage word count by label:")
display(df.groupby('label')['word_count'].mean())

print("\nAverage first-person pronoun count by label:")
display(df.groupby('label')['first_person_count'].mean())

from sklearn.feature_selection import SelectKBest, chi2

# Select top 20 most predictive words using chi-square test
selector = SelectKBest(score_func=chi2, k=20)
selector.fit(X, y)

feature_names = tfidf_vectorizer.get_feature_names_out()
top_features_idx = selector.get_support(indices=True)
top_features = feature_names[top_features_idx]
scores = selector.scores_[top_features_idx]

feature_scores = sorted(zip(top_features, scores), key=lambda x: x[1], reverse=True)

print("Top 20 most predictive words (chi-square scores):")
for word, score in feature_scores:
    print(f"{word}: {score:.2f}")

from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt

# Note: standard PCA doesn't work directly on sparse TF-IDF matrices,
# TruncatedSVD is the standard equivalent for sparse text data
svd = TruncatedSVD(n_components=2, random_state=42)
X_reduced = svd.fit_transform(X)

plt.figure(figsize=(8, 6))
plt.scatter(X_reduced[y==0, 0], X_reduced[y==0, 1], alpha=0.3, label='Non-Risk', s=5)
plt.scatter(X_reduced[y==1, 0], X_reduced[y==1, 1], alpha=0.3, label='Suicidal Ideation', s=5)
plt.xlabel('Component 1')
plt.ylabel('Component 2')
plt.title('2D Projection of TF-IDF Features (TruncatedSVD)')
plt.legend()
plt.savefig('/content/pca_visualization.png', dpi=150)
plt.show()

print(f"Explained variance ratio: {svd.explained_variance_ratio_}")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Split the resampled data into training and testing sets
print('Splitting data into training and testing sets...')
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
print('Data split complete. Training samples:', X_train.shape[0], 'Testing samples:', X_test.shape[0])

# --- Baseline Model: Logistic Regression ---
print('\nTraining Logistic Regression model...')
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_model.fit(X_train, y_train)
print('Logistic Regression model training complete.')

# Evaluate Logistic Regression model
y_pred_lr = logistic_model.predict(X_test)
y_proba_lr = logistic_model.predict_proba(X_test)[:, 1]

print('\nLogistic Regression Model Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_lr):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_lr):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_lr):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_lr):.4f}')
print(f'ROC-AUC: {roc_auc_score(y_test, y_proba_lr):.4f}')

# --- Baseline Model: Support Vector Machine (SVM) ---
print('\nTraining Support Vector Machine (SVM) model...')
svm_model = SVC(probability=True, random_state=42) # probability=True for ROC-AUC
svm_model.fit(X_train, y_train)
print('SVM model training complete.')

# Evaluate SVM model
y_pred_svm = svm_model.predict(X_test)
y_proba_svm = svm_model.predict_proba(X_test)[:, 1]

print('\nSupport Vector Machine (SVM) Model Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_svm):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_svm):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_svm):.4f}')
print(f'ROC-AUC: {roc_auc_score(y_test, y_proba_svm):.4f}')

"""## Advanced Model: Fine-tuned Transformer (BERT)"""

!pip install transformers==4.46.0 tensorflow==2.20.0 --quiet

!pip install transformers==4.46.0 tokenizers==0.20.3 tensorflow==2.20.0 --quiet --force-reinstall

import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.utils import class_weight
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

# Split the preprocessed text data for BERT (using the original processed_text and labels)
# Note: X_resampled from SMOTE was for TF-IDF, BERT requires raw text input.
print('Splitting original processed text data into training and testing sets for BERT...')
X_train_bert, X_test_bert, y_train_bert, y_test_bert = train_test_split(
    df['processed_text'].tolist(),
    df['label'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=df['label'].tolist() # Stratify to maintain class distribution
)
print(f'BERT Data split complete. Training samples: {len(X_train_bert)}, Testing samples: {len(X_test_bert)}')

# Load pre-trained tokenizer
print('\nLoading BERT tokenizer...')
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
print('Tokenizer loaded.')

# Tokenize the data
print('Tokenizing training data...')
train_encodings = tokenizer(X_train_bert, truncation=True, padding=True, max_length=128, return_tensors='tf')
print('Tokenizing testing data...')
test_encodings = tokenizer(X_test_bert, truncation=True, padding=True, max_length=128, return_tensors='tf')
print('Data tokenization complete.')

# Create TensorFlow Datasets
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    tf.constant(y_train_bert)
)).batch(16)

test_dataset = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings),
    tf.constant(y_test_bert)
)).batch(16)

# Calculate class weights for imbalanced dataset during BERT training
print('\nCalculating class weights...')
class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(y_train_bert), y=y_train_bert)
class_weight_dict = {i: weight for i, weight in enumerate(class_weights)}
print('Class weights calculated:', class_weight_dict)

# Load pre-trained BERT model for sequence classification
print('\nLoading BERT model...')
model = TFAutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
print('BERT model loaded.')

# Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metrics = [tf.keras.metrics.SparseCategoricalAccuracy('accuracy')]

model.compile(optimizer=optimizer, loss=loss, metrics=metrics)

# Train the model
print('\nTraining BERT model...')
# Convert class_weight_dict to a dict usable by Keras for class_weight argument
# Keras expects dictionary keys to be integers representing class labels.
# Our class_weight_dict already matches this format.
model.fit(
    train_dataset,
    epochs=3, # You can adjust the number of epochs
    batch_size=16,
    class_weight=class_weight_dict
)
print('BERT model training complete.')

# Evaluate the BERT model
print('\nEvaluating BERT model...')
predictions = model.predict(test_dataset)
logits = predictions.logits
y_pred_bert = np.argmax(logits, axis=1)
y_proba_bert = tf.nn.softmax(logits, axis=1)[:, 1].numpy()

print('\nBERT Model Evaluation:')
print(f'Accuracy: {accuracy_score(y_test_bert, y_pred_bert):.4f}')
print(f'Precision: {precision_score(y_test_bert, y_pred_bert):.4f}')
print(f'Recall: {recall_score(y_test_bert, y_pred_bert):.4f}')
print(f'F1-score: {f1_score(y_test_bert, y_pred_bert):.4f}')
print(f'ROC-AUC: {roc_auc_score(y_test_bert, y_proba_bert):.4f}')

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

cm_lr = confusion_matrix(y_test, y_pred_lr)
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[0].set_title('Logistic Regression')

cm_svm = confusion_matrix(y_test, y_pred_svm)
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='Blues', ax=axes[1],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[1].set_title('SVM')

cm_bert = confusion_matrix(y_test_bert, y_pred_bert)
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Blues', ax=axes[2],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[2].set_title('BERT')

plt.tight_layout()
plt.savefig('/content/confusion_matrices.png', dpi=150)
plt.show()

!pip install lime --quiet

import numpy as np
import tensorflow as tf

def bert_predict_proba(texts):
    # Tokenize the input texts the same way you did for training
    encodings = tokenizer(
        list(texts),
        truncation=True,
        padding=True,
        max_length=128,
        return_tensors="tf"
    )
    # Get raw model outputs
    outputs = model(encodings)
    logits = outputs.logits
    # Convert to probabilities
    probs = tf.nn.softmax(logits, axis=1).numpy()
    return probs

from lime.lime_text import LimeTextExplainer

explainer = LimeTextExplainer(class_names=["Non-Risk", "Suicidal Ideation"])

# Pick one example from your test set to explain
sample_text = X_test_bert[0]  # change the index to try different posts

exp = explainer.explain_instance(
    sample_text,
    bert_predict_proba,
    num_features=10,   # shows the top 10 words that influenced the decision
    num_samples=200    # lower this if it's running slow, raise it for more accuracy
)

exp.show_in_notebook(text=True)

# predictions = bert_predict_proba(X_test_bert)  # commented out, use batched version below instead

def bert_predict_proba_batched(texts, batch_size=32):
    all_probs = []
    for i in range(0, len(texts), batch_size):
        batch = list(texts[i:i+batch_size])
        encodings = tokenizer(
            batch,
            truncation=True,
            padding=True,
            max_length=128,
            return_tensors="tf"
        )
        outputs = model(encodings)
        probs = tf.nn.softmax(outputs.logits, axis=1).numpy()
        all_probs.append(probs)
    return np.concatenate(all_probs, axis=0)

predictions = bert_predict_proba_batched(X_test_bert, batch_size=32)
predicted_labels = np.argmax(predictions, axis=1)

misclassified_idx = [i for i in range(len(y_test_bert)) if predicted_labels[i] != y_test_bert[i]]
print(f"Number of misclassified examples: {len(misclassified_idx)}")
print(f"First few misclassified indices: {misclassified_idx[:5]}")

sample_text = X_test_bert[misclassified_idx[0]]
actual_label = y_test_bert[misclassified_idx[0]]
predicted_label = predicted_labels[misclassified_idx[0]]

print(f"Actual label: {'Suicidal Ideation' if actual_label == 1 else 'Non-Risk'}")
print(f"Predicted label: {'Suicidal Ideation' if predicted_label == 1 else 'Non-Risk'}")
print(f"\nPost text:\n{sample_text}")

sample_text = X_test_bert[misclassified_idx[0]]
actual_label = y_test_bert[misclassified_idx[0]]
predicted_label = predicted_labels[misclassified_idx[0]]

print(f"Actual label: {'Suicidal Ideation' if actual_label == 1 else 'Non-Risk'}")
print(f"Predicted label: {'Suicidal Ideation' if predicted_label == 1 else 'Non-Risk'}")
print(f"\nPost text:\n{sample_text}")

exp = explainer.explain_instance(sample_text, bert_predict_proba, num_features=10, num_samples=200)
exp.show_in_notebook(text=True)

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Logistic Regression
cm_lr = confusion_matrix(y_test, y_pred_lr)
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[0].set_title('Logistic Regression')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('Actual')

# SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='Blues', ax=axes[1],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[1].set_title('SVM')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('Actual')

# BERT
cm_bert = confusion_matrix(y_test_bert, y_pred_bert)
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Blues', ax=axes[2],
            xticklabels=['Non-Risk', 'Suicidal Ideation'],
            yticklabels=['Non-Risk', 'Suicidal Ideation'])
axes[2].set_title('BERT')
axes[2].set_xlabel('Predicted')
axes[2].set_ylabel('Actual')

plt.tight_layout()
plt.savefig('/content/confusion_matrices.png', dpi=150)
plt.show()

exp = explainer.explain_instance(sample_text, bert_predict_proba, num_features=10, num_samples=200)
exp.show_in_notebook(text=True)

!git clone https://github.com/publicmarks/suicide-ideation-detection-capstone.git

!mkdir -p suicide-ideation-detection-capstone/data/raw
!mkdir -p suicide-ideation-detection-capstone/notebooks
!mkdir -p suicide-ideation-detection-capstone/models
!mkdir -p suicide-ideation-detection-capstone/figures
!mkdir -p suicide-ideation-detection-capstone/reports

!cp /content/drive/MyDrive/[your CSV path] suicide-ideation-detection-capstone/data/raw/
!cp /content/eda_distributions.png suicide-ideation-detection-capstone/figures/
!cp /content/pca_visualization.png suicide-ideation-detection-capstone/figures/
!cp /content/confusion_matrices.png suicide-ideation-detection-capstone/figures/
!cp /content/logistic_regression_model.pkl suicide-ideation-detection-capstone/models/
!cp /content/svm_model.pkl suicide-ideation-detection-capstone/models/
!cp /content/tfidf_vectorizer.pkl suicide-ideation-detection-capstone/models/
!cp -r /content/bert_suicidal_ideation_model suicide-ideation-detection-capstone/models/

!find /content/drive/MyDrive -iname "*capstone*pdf*"